name: "Polygonal Zones"
description: "Helper Add-on for the polygonal zones integration."
version: "0.0.1"
slug: "polygonal_zones"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

startup: services
webui: http://[HOST]:[PORT:8000]/
ingress: true
ingress_port: 8000
ports:
  8000/tcp: 8000
