name: "Polygonal Zones"
description: "Helper Add-on for the polygonal zones integration."
version: "0.0.3"
slug: "polygonal_zones"
panel_icon: "mdi:map"

init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: system
ingress: true
ingress_port: 8000
ports:
  8000/tcp: 8000
